name: api-contract
on:
  pull_request:

jobs:
  drift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: truespec/action@v0
        with:
          spec-path: openapi.yaml
          fail-on: breaking
